// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
// Only load .env files in local dev (Vercel injects env vars directly)
if (!process.env.VERCEL) {
  dotenv.config({ path: ".env.local", override: false });
  dotenv.config({ path: ".env", override: false });
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
